config/routes.rb
Rails.application.routes.draw do
  resources :structures
  root "homepage#homepage"
  # devise_for :users

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/structure.rb
class Structure < ApplicationRecord
end

app/controllers/structures_controller.rb
class StructuresController < ApplicationController
  before_action :set_structure, only: %i[ show edit update destroy ]
  require "uri"
  require "net/http"

  # GET /structures or /structures.json
  def index
    @structures = Structure.all
    current_user_location = request.location.city
    puts current_user_location
    latitude = params[:l]
    longitude = params[:L]
    url = URI("https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=#{latitude},#{longitude}&radius=10000&type=pharmacy&keyword=pharmacy&key=AIzaSyAy_9GkemEqUHh4ueMlxhJOmqJLInzsKRM")
    puts url
    https = Net::HTTP.new(url.host, url.port)
    https.use_ssl = true

    request = Net::HTTP::Get.new(url)

    response = https.request(request).read_body
    response = JSON.parse(response)

    @results = response["results"]
    @results.each do |result|
      structure = Structure.find_by(place_id: result["place_id"])
      if structure.nil?
        Structure.create!(place_id: result["place_id"], name: result["name"])
      end
    end



    respond_to do |format|
      format.html {}
      format.json {render json: @results}
    end

    # puts response.read_body
  end

  # GET /structures/1 or /structures/1.json
  def show
  end

  # GET /structures/new
  def new
    @structure = Structure.new
  end

  # GET /structures/1/edit
  def edit
  end

  # POST /structures or /structures.json
  def create
    @structure = Structure.new(structure_params)

    respond_to do |format|
      if @structure.save
        format.html { redirect_to @structure, notice: "Structure was successfully created." }
        format.json { render :show, status: :created, location: @structure }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /structures/1 or /structures/1.json
  def update
    respond_to do |format|
      if @structure.update(structure_params)
        format.html { redirect_to @structure, notice: "Structure was successfully updated." }
        format.json { render :show, status: :ok, location: @structure }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /structures/1 or /structures/1.json
  def destroy
    @structure.destroy
    respond_to do |format|
      format.html { redirect_to structures_url, notice: "Structure was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_structure
      @structure = Structure.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def structure_params
      params.require(:structure).permit(:name, :contact, :email, :variety)
    end
end

app/helpers/structures_helper.rb
module StructuresHelper
end

app/views/structures/_form.html.erb
<%= form_with(model: structure, local: true) do |form| %>
  <% if structure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(structure.errors.count, "error") %> prohibited this structure from being saved:</h2>

      <ul>
        <% structure.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :contact %>
    <%= form.text_field :contact %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :variety %>
    <!--<%= form.text_field :variety %> -->
    <%= form.select :variety, ['Pharmacy', 'Hospital'] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/structures/edit.html.erb
<h1>Editing Structure</h1>

<%= render 'form', structure: @structure %>

<%= link_to 'Show', @structure %> |
<%= link_to 'Back', structures_path %>

app/views/structures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Structures</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Contact</th>
      <th>Email</th>
      <th>Variety</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @structures.each do |structure| %>
      <tr>
        <td><%= structure.name %></td>
        <td><%= structure.contact %></td>
        <td><%= structure.email %></td>
        <td><%= structure.variety %></td>
        <td><%= link_to 'Show', structure %></td>
        <td><%= link_to 'Edit', edit_structure_path(structure) %></td>
        <td><%= link_to 'Destroy', structure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h2>Google Answer</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Open ?</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody id="display">
  <% @results.each do |business| %>
    <tr>
      <td><%= business["name"] %></td>
      <td> <% if business["opening_hours"] %> Open <% else %> Close <% end %> </td>
      <td><%= business["rating"] %></td>
    </tr>
  <% end %>
  <tbody>

</table>
<%= link_to 'New Structure', new_structure_path %>

app/views/structures/index.js.erb
$(document).ready(function() {
    
    if (window.navigator.geolocation) {
        window.navigator.geolocation.window.navigator.geolocation.getCurrentPosition(console.log, console.log);
    } 
}) 

app/views/structures/new.html.erb
<h1>New Structure</h1>

<%= render 'form', structure: @structure %>

<%= link_to 'Back', structures_path %>

app/views/structures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @structure.name %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @structure.contact %>
</p>

<p>
  <strong>Email:</strong>
  <%= @structure.email %>
</p>

<p>
  <strong>Variety:</strong>
  <%= @structure.variety %>
</p>

<%= link_to 'Edit', edit_structure_path(@structure) %> |
<%= link_to 'Back', structures_path %>